# Generated by Django 5.0.6 on 2024-11-04 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_rename_contrat_customer_pdfid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='pdfid',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='typeid',
        ),
    ]
