# Generated by Django 5.0.6 on 2024-11-04 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_remove_customer_created_at_remove_customer_gender_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
