# Generated by Django 5.0.6 on 2024-11-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0012_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='title',
        ),
    ]
