# Generated by Django 5.0.6 on 2024-11-03 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_stagiaires_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagiaires',
            name='photo',
        ),
    ]
