# Generated by Django 5.0.6 on 2024-11-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_remove_stagiaires_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=45)),
                ('prenom', models.CharField(max_length=45)),
                ('photo', models.FileField(blank=True, null=True, upload_to='pdf_contrats/')),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=12)),
            ],
        ),
    ]
