# Generated by Django 5.0.6 on 2024-11-03 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_customer_employee_supplier_visitor_delete_employe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='title',
        ),
    ]
