# Generated by Django 5.0.6 on 2024-11-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_remove_employee_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='genre',
            new_name='gender',
        ),
    ]
