# Generated by Django 5.0.6 on 2024-11-03 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_rename_genre_employee_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='genre',
            new_name='gender',
        ),
    ]
