# Generated by Django 5.0.6 on 2024-11-04 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_rename_genre_customer_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='contrat',
            new_name='pdfid',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='title',
            new_name='typeid',
        ),
    ]
