# Generated by Django 5.0.6 on 2024-11-04 08:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0011_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=455)),
                ('surname', models.CharField(max_length=455)),
                ('email', models.EmailField(max_length=254)),
                ('adress', models.CharField(max_length=455)),
                ('telephone', models.CharField(max_length=12)),
                ('typeid', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('pdfid', models.FileField(upload_to='pdf_contrats/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
