# Generated by Django 5.0.6 on 2024-11-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0013_remove_supplier_surname_remove_supplier_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
