# Generated by Django 5.0.6 on 2024-11-04 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0016_post_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='post_name',
        ),
    ]
