# Generated by Django 5.0.6 on 2024-11-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0018_alter_employee_post_alter_post_post_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=120)),
                ('house_price', models.CharField(max_length=120)),
            ],
        ),
    ]
