# Generated by Django 5.0.6 on 2024-11-04 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0019_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Maison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.house'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='montant_unitaire',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
