# Generated by Django 5.1.4 on 2024-12-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0022_remove_booking_maison_remove_booking_customer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
        ),
    ]
